### ISSUE TITLE
seg fault or runaway memory usage with certain inputs

### ISSUE THREAD

**Issue by wluker** [sfilip/firpm#2] opened 2018-04-18 14:29 UTC
Interesting work. Thank you for sharing it.

I was trying out the double precision variant of firpm and the following causes a seg fault on Linux with gcc.

    PMOutput result = firpm(20, {0.0, 0.4, 0.6, 0.64, 0.69, 0.74, 0.79, 0.83, 0.88, 1.0}, {1.0, 1.0, 0.0, 0.0, 1.0, 1.0, 0.0, 0.0, 1.0, 1.0}, {1.0, 1.0, 1.0, 1.0, 1.0});

And this code causes runaway memory usage. (Make sure to ctrl-c before you run out of memory)

    PMOutput result = firpm(12, {0.0, 0.4, 0.6, 0.6089285714285714, 0.6178571428571429, 0.6267857142857143, 0.6357142857142857, 0.6446428571428571, 0.6535714285714286, 0.6625, 0.6714285714285714, 0.6803571428571428, 0.6892857142857143, 0.6982142857142857, 0.7071428571428571, 0.7160714285714285, 0.725, 0.7339285714285714, 0.7428571428571429, 0.7517857142857143, 0.7607142857142857, 0.7696428571428571, 0.7785714285714285, 0.7874999999999999, 0.7964285714285714, 0.8053571428571428, 0.8142857142857143, 0.8232142857142857, 0.8321428571428571, 0.8410714285714285, 0.85, 0.8589285714285714, 0.8678571428571429, 0.8767857142857143, 0.8857142857142857, 0.8946428571428571, 0.9035714285714285, 0.9124999999999999, 0.9214285714285714, 0.9303571428571428, 0.9392857142857143, 0.9482142857142857, 0.9571428571428571, 0.9660714285714285, 0.975, 1.0}, {1.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0}, {87.35985578898647, 1000.0, 1029.7619047619048, 1059.5238095238094, 1089.2857142857144, 1119.047619047619, 1148.8095238095239, 1178.5714285714284, 1208.3333333333333, 1238.0952380952383, 1267.857142857143, 1297.6190476190475, 1327.3809523809523, 1357.142857142857, 1386.904761904762, 1416.6666666666667, 1446.4285714285716, 1476.1904761904761, 1505.952380952381, 1535.7142857142858, 1565.4761904761906, 1595.2380952380952, 1625.0});

**Comment by sfilip** [comment] 2018-04-19 08:14
Hi @wluker ! Thank you for your comment and for sharing this. I'll look into it and figure out what the issues are.

**Comment by 0joshuaolson1** [comment] 2018-07-04 15:40
I reproduced both problems with all three precisions. Is it likely that [fquantizer](https://github.com/sfilip/fquantizer/blob/89c00ead3e2f178ce469f626e1d8aa3333da2d7d/src/pm.cpp#L624) is incorrect too?

**Comment by jlwehle** [comment] 2019-11-06 04:16
In trying a particular filter specification with your firpm I was able to
trigger various crashes.  The platform I'm using is FreeBSD 11.3 with the
OS supplied compiler (clang version 8.0.1).

Issues fixed by the enclosed patch:

  1) Both firpm and firpmRS have lambdas of the form:

       freqBands[i].amplitude = [=](BandSpace bSpace, long double x) ...

     Unfortunately the [=] appears to cause the a and freqBands arrays to be
     copied over and over.  The net effect is the process consumed 64 GBytes
     of memory before dying.

  2) initUniformExtremas has code of the form:

       buffer = bandwidths[nonPointBands[i]] / avgDistance;
       buffer += 0.5;
       B[nonPointBands[i]].extremas = lrint(buffer) + 1;
     
     This appears to occasionally result in double rounding.  The net effect
     is B[nonPointBands[nonPointBands.size() - 1u]].extremas attempts to go
     below zero so it wraps to a large number causing a crash when executing:

       omega[startIndex + B[i].extremas - 1] = B[i].stop;

  3) initUniformExtremas can be called by firpmRS with an omega array
     that's smaller than the band array.  This results in avgDistance
     being negative so latter extremas calculations wrap to a large
     number causing a crash when executing:

       omega[startIndex + B[i].extremas - 1] = B[i].stop;

  4) If firpmRS calls exchange which fails, then output.x will be empty.
     This causes referenceScaling to crash when executing:

       newX.push_back(x[offset]);

Notes:

  a) These same changes probably should be propagated to both firpm_d
     and firpm_mp.

-- John
[PatchJLW01.txt](https://github.com/sfilip/firpm/files/3812468/PatchJLW01.txt)

**Comment by sfilip** [comment] 2019-11-07 07:55
Hi @jlwehle! Thank you for pointing out all these problems + the fixes. I'm currently integrating them and fixing some other build issues that I encountered when using the code with OS X and clang. For any new changes you suggest, it might be simpler if you fork the project, apply the changes to your fork and then issue a pull request. I'd then be happy to review everything, add the equivalent changes to the other versions, if needed, and merge into the master branch. 

I still want to make changes to the code before closing this issue.

**Comment by jlwehle** [comment] 2019-11-22 03:43
I seem to be getting the desired results when using firpm_d, firpm_ld, and firpm_mp from the updated master branch to generate some low pass filters which previously failed.

Thanks for the code updates.

Will these changes be propagated into fquantizer?

**Comment by sfilip** [comment] 2019-11-22 12:48
No problem. And thanks for the interest in these projects and signaling all the issues and fixes. It gave me the jolt I needed to finally revise the code.

Regarding fquantizer, yes I plan to propagate these changes there as well. Currently still refactoring a bit in this repository and I have some other things on my plate as well, but I'll try to get around to fquantizer soon.

**Comment by sfilip** [comment] 2019-11-25 11:18
Closing this issue since the problematic inputs mentioned here should now be appropriately processed.

**Closed as completed by sfilip** 2019-11-25 11:18 UTC
